//CHATBOT
export const SEND_MESSAGE_SAGA = 'SEND_MESSAGE_SAGA';

//VIDEO
export const GET_VIDEO_SAGA = 'GET_VIDEO_SAGA';

//NEWS
export const GET_NEWS_SAGA = 'GET_NEWS_SAGA';

//PRODUCTS
export const GET_PRODUCTS_SAGA = 'GET_PRODUCTS_SAGA';
